apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-role-binding
subjects:
  - kind: ServiceAccount
    name: s3-access-sa
roleRef:
  kind: Role
  name: namespace-role
  apiGroup: rbac.authorization.k8s.io
