apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "delete"]
